### ISSUE TITLE
\src\gonum.org\v1\gonum\lapack\gonum\lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )

### ISSUE THREAD

**Issue by iamapickle** [go-gota/gota#120] opened 2020-05-20 04:14 UTC
on go doing 
 go get github.com/go-gota/gota/dataframe
im getting the above mentioned error
in the line 
    dlamchE = 0x1p-53

**Comment by julienrbrt** [comment] 2020-06-11 18:10
I personally could not reproduce. Do you still have that issue?

**Comment by kniren** [comment] 2020-06-18 07:46
Can't reproduce either. It was probably fixed upstream in gonum. Closing the issue.

**Closed by kniren** 2020-06-18 07:46 UTC
